version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    depends_on:
      custom-migration:
        condition: service_completed_successfully
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017/notifications?authSource=admin
    networks:
      - app-network
  
  custom-migration:
    build:
      context: .
      dockerfile: migrations/Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge